name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add additional steps to build your project
      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # Add deployment steps
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2
        with:
          server: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          source: "path/to/your/local/project"
          remote_path: "${{ secrets.REMOTE_PATH }}"

      # Add more steps as needed, such as testing, database migration, etc.
      - name: Run tests
        run: npm test

      - name: Database migration
        run: |
          # Add commands to run database migration script
          # Example:
          # php artisan migrate

      # Add any additional steps for your application deployment process
